'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import { RecoilRoot } from "recoil";
import Footer from '@/components/Footer'

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Travel App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <RecoilRoot>
        <body className={inter.className}>
          <Nav/>
          {children}
          <Footer/>
        </body>
      </RecoilRoot>
    </html>
  );
}
